# The Guestbook app is configured to use skaffold modules.
# The frontend and backend services can be activated by name,
# allowing each service to be iterated on independently.
# To learn more about skaffold modules and multi-config support,
# visit https://skaffold.dev/docs/design/config/

apiVersion: skaffold/v4beta11
kind: Config
requires:
  - path: ./src/frontend
  - path: ./src/backend
build:
  local:
    concurrency: 0
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}
