version: '3.4'

services:
  #--------------------
  goexperiments:
    image: basicmq
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  
  #--------------------
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

networks:
  rabbitmq:
    driver: bridge