global:
  scrape_interval: 5s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: 
        - "localhost:9090"

  - job_name: "demo"
    static_configs:
    - targets:
      - demo.promlabs.com:10000
      - demo.promlabs.com:10001
      - demo.promlabs.com:10002