version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: goddess
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./store/config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  pgdata:
