# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: go-guestbook-frontend
      context: .
manifests:
  rawYaml:
    - ./kubernetes-manifests/*.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: go-guestbook-frontend
    port: 80
    localPort: 4503
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}
