services:

  app:
    container_name: redgoddess
    build:
      context: .
      dockerfile: ./dev.dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
