version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - db_url=postgres://postgres:secret@postgres:5432/postgres?sslmode=disable
      - port=8080
      - prometheus_port=9000
      - otlp_endpoint=jaeger:16686
      - dev=true
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-ddl.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/config/prometheus.yml
    volumes:
      - ./configs/prometheus.yml:/etc/config/prometheus.yml
    ports:
      - "9000:9000"

  grafana:
    image: grafana/grafana
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards/
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
